name: "Atlassian Data Center AWS Infrastructure"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: eu-central-1
  TF_IN_AUTOMATION: "true"

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: |
          terraform init -backend=false
          terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: fmt-validate
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Configure AWS creds (STATE)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::010438507485:role/GitHubActions-Terraform-State
          aws-region: eu-central-1

      - name: Terraform init (remote state)
        run: terraform init -backend-config=env/backend-config.hcl

      - name: Switch to DEPLOY role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::010438507485:role/GitHubActions-Terraform-Deploy
          aws-region: eu-central-1

      - name: Terraform plan
        run: terraform plan -var-file=tfvars/asi.tfvars

  apply:
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Configure AWS creds (STATE)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::010438507485:role/GitHubActions-Terraform-State
          aws-region: eu-central-1

      - name: Terraform init (remote state)
        run: terraform init -backend-config=env/backend-config.hcl

      - name: Switch to DEPLOY role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::010438507485:role/GitHubActions-Terraform-Deploy
          aws-region: eu-central-1

      - name: Terraform apply (auto-approve)
        run: terraform apply -auto-approve -var-file=tfvars/asi.tfvars
